
[subsection CriTcl]

To build Struct the tool [syscmd critcl] is required.

[para] Struct's build system accepts it either as an application found
in the PATH, or as a Tcl package available to the [syscmd tclsh] used
to run their build & installation processes.

[para] Struct [emph must] have version 3.1.1, and
[package critcl::class] version 1.0.3, or higher.

[para] The github repository for critcl can be found at
[uri http://jcw.github.com/critcl].

[para] At the above url is also an explanation on how to build and
install CriTcl, including a list of its dependencies.

[para] Its instructions will not be repeated here. If there are
problems with their directions please file a bug against the critcl
project, and not Struct.
